spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parking-lot
    username: root
    password: Ban@4577
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  batch:
    jdbc:
      initialize-schema: always

